[package]
name = "argent_gifting"
version = "0.1.0"
edition = "2023_11"


[dependencies]
starknet = "2.6.3"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.24.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.13.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "cairo-v2.6.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
max-line-length = 120
sort-module-level-items = true

[scripts]
test = "snforge test"
start-devnet = "pnpm exec tsc && pnpm exec tsx scripts/ensure-devnet.ts"
kill-devnet = "docker stop devnet"
test-ts = "scarb --profile release build && pnpm exec tsc && pnpm exec tsx scripts/ensure-devnet.ts && pnpm exec mocha --spec \"tests-integration/**/*.test.ts\""
profile = "scarb --profile release build && pnpm exec tsc && pnpm exec tsx scripts/ensure-devnet.ts && pnpm exec tsx scripts/profile.ts"
format = "scarb fmt && pnpm exec prettier --write ."
deploy = "scarb --profile release build &&  pnpm exec tsx scripts/deploy.ts"
