[package]
name = "argent_gifting"
version = "0.1.0"
edition = "2023_11"


[dependencies]
starknet = "2.6.3"
openzeppelin = "1.0.0"
alexandria_math = "0.5.0"

[[target.starknet-contract]]
sierra = true
casm = true


[dev-dependencies]
snforge_std = "0.57.0"
assert_macros = "2.10.1"

[tool.fmt]
max-line-length = 120
sort-module-level-items = true

[scripts]
test = "snforge test"
start-devnet = "docker build -t devnet . && docker run -d -p 127.0.0.1:5050:5050 devnet"
kill-devnet = "docker ps -q --filter 'ancestor=devnet' | xargs docker stop"
test-ts = "scarb --profile release build && yarn tsc && yarn mocha tests-integration/*.test.ts"
profile = "scarb --profile release build && node --loader ts-node/esm scripts/profile.ts"
format = "scarb fmt && yarn prettier --write ."
deploy = "scarb --profile release build && node --loader ts-node/esm scripts/deploy.ts"
