name: Integration CI

on:
  push:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1.6.0
          
      - name: Install project
        run: pnpm install --frozen-lockfile

      - name: Start devnet in background
        run: scarb run start-devnet

      - name: Run integration tests
        run: scarb run test-ts

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install project
        run: pnpm install --frozen-lockfile

      - name: Check correct formatting
        run: pnpm format

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install project
        run: pnpm install --frozen-lockfile

      - name: Check correct linting
        run: pnpm lint

  gas-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1.6.0
          
      - name: Install project
        run: pnpm install --frozen-lockfile

      - name: Start devnet in background
        run: scarb run start-devnet

      - name: Gas report
        run: scarb run profile --check
